/*
 * baryon_variants_corr_claude.cc
 *
 * Single-baryon two-point functions of the SU(Nc=4), one-flavour SDM B-form operators
 * (the 9 highest-weight |J^P,(n_+,n_-),J,M=J> operators of baryon_theory_claude.md
 * Sec. 4.1, or any state of the 35-state table) from the full Pauli-Dirac propagator
 * dump of point2all_prop_dumper_full_claude.cc.
 *
 *   C_{AA'}(t) = sum_x < B_A(x,t) B^\dagger_{A'}(0) >
 *              = P(A') sum_{a,b} \epsilon_a \epsilon_b det_{ij}[ G^{a_i b_j}_{A_i A'_j}(x,0) ]
 *   C_{OO'}(t) = sum_{A,A'} c^O_A conj(c^{O'}_{A'}) C_{AA'}(t)
 *
 * Term tables (baryon_variants_terms_claude.txt) and operator coefficients
 * (baryon_variants_ops_claude.txt / _all_) are text files generated by the Python
 * scripts; see baryon_variants_impl_plan_claude.md. Contraction kernel, readers and the
 * naive reference live in baryon_pd_common_claude.h.
 *
 * CLI:
 *   --src <file.pdfull.lime>      propagator dump (default ColdConfig.pdfull.lime)
 *   --out <file.h5>               output (default ColdConfig.bvar.h5)
 *   --terms <file>                term tables (default baryon_variants_terms_claude.txt)
 *   --ops <file>                  operator tables (default baryon_variants_ops_claude.txt)
 *   --op <name> | all             operator whose J^P block is computed (default all)
 *   --pairs block | sector | all  elementary pairs to compute and store (default block):
 *                                   block  = the pairs the selected block(s) need
 *                                   sector = every pair of the term file in the same
 *                                            (parity, J_3 mod 4) sector(s)
 *                                   all    = every pair of the term file
 *   --naive-check <nsample>       compare the kernel density with the naive Wick-form
 *                                 loop at nsample sites (0 = all sites) on corner 0
 *   --kernel-mode 0|1             site kernel variant (0 = gather sub-elements from the
 *                                 view [default], 1 = read the whole site object); both
 *                                 validated, identical results
 *   --cross                       also form C_{OO'} for operator pairs from DIFFERENT
 *                                 blocks whose elementary pairs are available
 *                                 (validation only: they vanish on the free field)
 *   --config <nersc>              gauge config, only needed for --sink-smear
 *   --sink-smear <w> <N>          also compute with a covariant Gaussian smeared sink
 *   --grid / --mpi                Grid layout
 *
 * HDF5 datasets (CorrFile = vector<Complex> of length T, compound (re,im)):
 *   meta, Cel_<A>_<A'> (corner average), Cop_<O>_<O'> (all pairs of each computed
 *   block); with --sink-smear also Celss_*, Copss_*.
 */

#include <Grid/Grid.h>
#include <algorithm>
#include <vector>
#include <sstream>
#include <memory>
#include <set>
#include <iomanip>
#include <fstream>

#include "baryon_pd_common_claude.h"

using namespace std;
using namespace Grid;

// Run metadata written alongside the correlators.
class BvarMeta: Serializable {
public:
  GRID_SERIALIZABLE_CLASS_MEMBERS(BvarMeta,
    std::string,         config,
    double,              mass,
    double,              M5,
    double,              b,
    double,              c,
    int,                 Ls,
    int,                 T,
    int,                 nCorner,
    double,              smearWidth,
    int,                 smearNiter,
    double,              sinkSmearWidth,
    int,                 sinkSmearNiter,
    std::string,         termsFile,
    std::string,         opsFile,
    std::string,         pairMode,
    std::string,         opNames,      // comma-joined
    std::string,         opJP,         // comma-joined, same order
    std::string,         opDef,        // per op "name:A=c;A=c", joined by "|"
    std::string,         pairList);    // comma-joined "A_A'"
};

// 2 J_3 = (n_0 + n_2) - (n_1 + n_3) of a tuple string.
static int J3TwiceOf(const std::string &tuple)
{
  int up = 0;
  int down = 0;
  for(size_t i=0; i<tuple.size(); i++){
    int d = tuple[i] - '0';
    if( d % 2 == 0 ) up++;
    else down++;
  }
  return up - down;
}

static bool SameSector(const std::string &a, const std::string &b)
{
  if( PDTermTable::ParityOf(a) != PDTermTable::ParityOf(b) ) return false;
  int d = J3TwiceOf(a) - J3TwiceOf(b);
  if( d < 0 ) d = -d;
  if( (d % 8) != 0 ) return false;
  return true;
}

static std::string JoinStrings(const std::vector<std::string> &v, const std::string &sep)
{
  std::string out;
  for(size_t i=0; i<v.size(); i++){
    if( i > 0 ) out += sep;
    out += v[i];
  }
  return out;
}

// Contract all selected pairs of one propagator and accumulate the time-slice sums.
static void ContractAll(PDTermTable &terms, const std::vector<int> &pairs,
                        const LatticePropagator &G, int T,
                        std::vector<std::vector<Complex> > &Cel)
{
  LatticeComplex dens(G.Grid());
  std::vector<TComplex> sl;
  for(size_t k=0; k<pairs.size(); k++){
    int p = pairs[k];
    double t0 = usecond();
    terms.ContractPair(G, p, dens);
    sliceSum(dens, sl, Tdir);
    double t1 = usecond();
    for(int t=0; t<T; t++){
      Cel[k][t] += TensorRemove(sl[t]);
    }
    std::cout << GridLogMessage << "  pair " << terms.A[p] << " " << terms.Ap[p]
              << " (" << terms.nterm[p] << " terms) " << (t1 - t0) / 1.0e6 << " s"
              << "  C(0) = " << TensorRemove(sl[0]) << std::endl;
  }
}

// Host evaluation of the det form for one site from the term table (independent of the
// device kernel): sum_terms w * Det4(G[rows, cols]).
static Complex HostTableDensity(const PDTermTable &terms, int p, const SpinColourMatrix &Gs)
{
  Complex val(0.0, 0.0);
  for(int k=0; k<terms.nterm[p]; k++){
    const int *t = &terms.idx[0] + 8 * (terms.offset[p] + k);
    Complex M[16];
    for(int i=0; i<4; i++){
      int sr = t[i] / Nc;
      int cr = t[i] % Nc;
      for(int j=0; j<4; j++){
        int sc = t[4+j] / Nc;
        int cc = t[4+j] % Nc;
        M[4*i+j] = Gs()(sr,sc)(cr,cc);
      }
    }
    val = val + Complex(terms.w[terms.offset[p] + k], 0.0) * Det4(M);
  }
  return val;
}

// Naive check: kernel density vs (i) the host det-form sum over the same term table and
// (ii) the naive Wick-form host loop, at sampled sites. Reports the worst site per pair.
static bool NaiveCheck(PDTermTable &terms, const std::vector<int> &pairs,
                       const LatticePropagator &G, int nsample)
{
  GridBase *grid = G.Grid();
  Coordinate latt = grid->FullDimensions();
  long vol = 1;
  for(int mu=0; mu<Nd; mu++) vol *= latt[mu];
  long stride = 1;
  if( nsample > 0 ){
    stride = vol / nsample;
    if( stride < 1 ) stride = 1;
  }
  PDNaive naive;
  LatticeComplex dens(grid);
  RealD maxKH = 0.0;   // kernel vs host det form
  RealD maxHN = 0.0;   // host det form vs naive
  long nchecked = 0;
  for(size_t k=0; k<pairs.size(); k++){
    int p = pairs[k];
    terms.ContractPair(G, p, dens);
    RealD pKH = 0.0;
    RealD pHN = 0.0;
    Coordinate worst(Nd, 0);
    Complex wk, wh, wn;
    for(long site=0; site<vol; site+=stride){
      Coordinate coor(Nd);
      Lexicographic::CoorFromIndex(coor, site, latt);
      SpinColourMatrix Gs;
      peekSite(Gs, G, coor);
      TComplex dv;
      peekSite(dv, dens, coor);
      Complex kern = TensorRemove(dv);
      Complex host = HostTableDensity(terms, p, Gs);
      Complex ref  = naive.SiteDensity(Gs, terms.A[p], terms.Ap[p]);
      RealD scale = std::max(1.0e-30, abs(ref));
      RealD rKH = abs(kern - host) / scale;
      RealD rHN = abs(host - ref) / scale;
      if( rKH > pKH ){
        pKH = rKH;
        worst = coor;
        wk = kern;
        wh = host;
        wn = ref;
      }
      pHN = std::max(pHN, rHN);
      nchecked++;
    }
    maxKH = std::max(maxKH, pKH);
    maxHN = std::max(maxHN, pHN);
    std::cout << GridLogMessage << "  naive-check pair " << terms.A[p] << " " << terms.Ap[p]
              << " rel(kernel,hostdet) = " << pKH << " rel(hostdet,naive) = " << pHN
              << " worst site (" << worst[0] << "," << worst[1] << "," << worst[2] << "," << worst[3]
              << ") kernel " << wk << " hostdet " << wh << " naive " << wn << std::endl;
  }
  std::cout << GridLogMessage << "naive-check: " << nchecked << " site evaluations, max rel(kernel,hostdet) = "
            << maxKH << ", max rel(hostdet,naive) = " << maxHN << std::endl;
  bool ok = ( maxKH < 1.0e-10 && maxHN < 1.0e-10 );
  if( ok ) std::cout << GridLogMessage << "naive-check PASSED." << std::endl;
  else     std::cout << GridLogMessage << "naive-check FAILED (continuing for diagnostics)." << std::endl;
  return ok;
}

int main(int argc, char ** argv)
{
  Grid_init(&argc, &argv);

  Coordinate latt        = GridDefaultLatt();
  Coordinate simd_layout = GridDefaultSimd(Nd, vComplex::Nsimd());
  Coordinate mpi_layout  = GridDefaultMpi();
  GridCartesian * UGrid  = SpaceTimeGrid::makeFourDimGrid(latt, simd_layout, mpi_layout);
  GridCartesian * UGridF = SpaceTimeGrid::makeFourDimGrid(latt, GridDefaultSimd(Nd, vComplexF::Nsimd()), mpi_layout);
  const int T = latt[Tdir];

  // ------------------------------------------------------------------
  // CLI
  // ------------------------------------------------------------------
  std::string srcFile   = "ColdConfig.pdfull.lime";
  std::string outFile   = "ColdConfig.bvar.h5";
  std::string termsFile = "baryon_variants_terms_claude.txt";
  std::string opsFile   = "baryon_variants_ops_claude.txt";
  std::string opName    = "all";
  std::string pairMode  = "block";
  std::string configFile;
  bool  doNaive     = false;
  int   naiveSample = 0;
  bool  doCross     = false;
  bool  naiveOK     = true;
  int   kernelMode  = 0;
  bool  doSinkSmear = false;
  RealD sinkSmearWidth = 0.0;
  int   sinkSmearNiter = 0;
  for(int i=0; i<argc; i++){
    std::string a(argv[i]);
    if( a == "--src" )    srcFile   = argv[i+1];
    if( a == "--out" )    outFile   = argv[i+1];
    if( a == "--terms" )  termsFile = argv[i+1];
    if( a == "--ops" )    opsFile   = argv[i+1];
    if( a == "--op" )     opName    = argv[i+1];
    if( a == "--pairs" )  pairMode  = argv[i+1];
    if( a == "--config" ) configFile = argv[i+1];
    if( a == "--cross" )  doCross = true;
    if( a == "--kernel-mode" ) kernelMode = std::stoi(argv[i+1]);
    if( a == "--naive-check" ){
      doNaive = true;
      naiveSample = std::stoi(argv[i+1]);
    }
    if( a == "--sink-smear" ){
      sinkSmearWidth = stod(argv[i+1]);
      sinkSmearNiter = std::stoi(argv[i+2]);
      doSinkSmear = (sinkSmearWidth > 0.0 && sinkSmearNiter > 0);
    }
  }
  assert( (pairMode == "block" || pairMode == "sector" || pairMode == "all") && "--pairs must be block|sector|all" );
  std::cout << GridLogMessage << "src = " << srcFile << ", out = " << outFile << std::endl;
  std::cout << GridLogMessage << "terms = " << termsFile << ", ops = " << opsFile << std::endl;
  std::cout << GridLogMessage << "op = " << opName << ", pairs = " << pairMode << std::endl;

  // ------------------------------------------------------------------
  // Tables and operator / block selection.
  // ------------------------------------------------------------------
  PDTermTable terms;
  terms.Read(termsFile);
  PDOperatorTable optab;
  optab.Read(opsFile);

  std::vector<int> blocks;     // block indices to compute
  if( opName == "all" ){
    for(int b=0; b<(int)optab.blockJP.size(); b++) blocks.push_back(b);
  } else {
    int b = optab.BlockOf(opName);
    assert( b >= 0 && "--op name not found in the operator table blocks" );
    blocks.push_back(b);
  }
  std::vector<std::string> selOps;   // operators of the selected blocks (in block order)
  for(size_t ib=0; ib<blocks.size(); ib++){
    int b = blocks[ib];
    for(size_t i=0; i<optab.blockOps[b].size(); i++) selOps.push_back(optab.blockOps[b][i]);
  }
  std::cout << GridLogMessage << "computing " << blocks.size() << " block(s), operators: "
            << JoinStrings(selOps, ",") << std::endl;

  // Elementary pairs needed by the selected blocks (ordered (A, A') over all operator
  // pairs of each block), and the pairs to compute according to --pairs.
  std::set<std::pair<std::string,std::string> > needed;
  for(size_t ib=0; ib<blocks.size(); ib++){
    int b = blocks[ib];
    for(size_t i=0; i<optab.blockOps[b].size(); i++){
      for(size_t j=0; j<optab.blockOps[b].size(); j++){
        const PDOperator &oi = optab.ops[optab.Find(optab.blockOps[b][i])];
        const PDOperator &oj = optab.ops[optab.Find(optab.blockOps[b][j])];
        for(size_t ci=0; ci<oi.comp.size(); ci++){
          for(size_t cj=0; cj<oj.comp.size(); cj++){
            needed.insert(std::make_pair(oi.comp[ci], oj.comp[cj]));
          }
        }
      }
    }
  }
  std::vector<int> pairs;     // indices into terms
  for(int p=0; p<terms.NPairs(); p++){
    bool take = false;
    if( pairMode == "all" ){
      take = true;
    } else if( pairMode == "block" ){
      take = ( needed.count(std::make_pair(terms.A[p], terms.Ap[p])) > 0 );
    } else {
      // sector: same (parity, J_3 mod 4) as any component of the selected operators
      for(size_t i=0; i<selOps.size() && !take; i++){
        const PDOperator &o = optab.ops[optab.Find(selOps[i])];
        for(size_t ci=0; ci<o.comp.size() && !take; ci++){
          if( SameSector(terms.A[p], o.comp[ci]) && SameSector(terms.Ap[p], o.comp[ci]) ) take = true;
        }
      }
    }
    if( take ) pairs.push_back(p);
  }
  // every needed pair must be available
  std::set<std::pair<std::string,std::string> >::iterator it;
  for(it=needed.begin(); it!=needed.end(); ++it){
    int p = terms.Find(it->first, it->second);
    assert( p >= 0 && "a pair needed by the selected operators is missing from the term file" );
    bool present = false;
    for(size_t k=0; k<pairs.size(); k++){
      if( pairs[k] == p ) present = true;
    }
    assert( present && "a needed pair was not selected (internal)" );
  }
  std::cout << GridLogMessage << "elementary pairs to compute: " << pairs.size()
            << " (needed by the blocks: " << needed.size() << ")" << std::endl;
  terms.Upload();
  terms.kernelMode = kernelMode;
  std::cout << GridLogMessage << "kernel mode " << kernelMode << " (0 = sub-element gather, 1 = whole site object)" << std::endl;

  // ------------------------------------------------------------------
  // Optional gauge field for sink smearing.
  // ------------------------------------------------------------------
  std::vector<LatticeColourMatrix> U(Nd, UGrid);
  if( doSinkSmear ){
    LatticeGaugeField Umu(UGrid);
    if( configFile.size() > 0 ){
      FieldMetaData header;
      NerscIO::readConfiguration(Umu, header, configFile);
      std::cout << GridLogMessage << "sink smearing with gauge config " << configFile << std::endl;
    } else {
      SU<Nc>::ColdConfiguration(Umu);
      std::cout << GridLogMessage << "sink smearing with COLD gauge field (no --config)" << std::endl;
    }
    SpatialLinks(Umu, U);
    std::cout << GridLogMessage << "sink smear: width " << sinkSmearWidth << " niter " << sinkSmearNiter << std::endl;
  }

  // ------------------------------------------------------------------
  // Corner loop: read one corner's 16 blocks, contract, accumulate.
  // ------------------------------------------------------------------
  std::vector<std::vector<Complex> > Cel(pairs.size(), std::vector<Complex>(T, Complex(0.0, 0.0)));
  std::vector<std::vector<Complex> > Celss(pairs.size(), std::vector<Complex>(T, Complex(0.0, 0.0)));
  PropRecord rec0;
  int nCorner = 0;
  {
    LatticePropagator G(UGrid);
    int corner = 0;
    while( true ){
      PropRecord rec;
      double t0 = usecond();
      int seen = ReadPDFullCorner(srcFile, UGrid, UGridF, corner, G, rec);
      double t1 = usecond();
      if( corner == 0 ){
        rec0 = rec;
        nCorner = seen;
        std::cout << GridLogMessage << "dump has " << nCorner << " corner(s); config " << rec.config
                  << " mass " << rec.mass << " M5 " << rec.M5 << " smear w " << rec.smearWidth
                  << " N " << rec.smearNiter << std::endl;
      }
      std::cout << GridLogMessage << "=== corner " << corner << " (" << rec.srcCoord[0] << ","
                << rec.srcCoord[1] << "," << rec.srcCoord[2] << "," << rec.srcCoord[3]
                << ") read in " << (t1 - t0) / 1.0e6 << " s, norm2(G) = " << norm2(G) << std::endl;

      if( doNaive && corner == 0 ){
        naiveOK = NaiveCheck(terms, pairs, G, naiveSample);
      }

      std::cout << GridLogMessage << "point sink:" << std::endl;
      ContractAll(terms, pairs, G, T, Cel);

      if( doSinkSmear ){
        LatticePropagator Gs(UGrid);
        Gs = G;
        CovariantSmearing<PeriodicGimplD>::GaussianSmear(U, Gs, sinkSmearWidth, sinkSmearNiter, Tdir);
        std::cout << GridLogMessage << "smeared sink:" << std::endl;
        ContractAll(terms, pairs, Gs, T, Celss);
      }

      corner++;
      if( corner >= nCorner ) break;
    }
  }
  for(size_t k=0; k<pairs.size(); k++){
    for(int t=0; t<T; t++){
      Cel[k][t]   = Cel[k][t]   / (RealD)nCorner;
      Celss[k][t] = Celss[k][t] / (RealD)nCorner;
    }
  }

  // ------------------------------------------------------------------
  // Operator correlators C_{OO'} for every ordered pair inside each computed block.
  // ------------------------------------------------------------------
  // Operator pairs: all ordered pairs inside each computed block; with --cross also
  // the pairs across blocks whose elementary pairs were computed (skipped otherwise).
  std::vector<std::string> copNames;
  std::vector<std::vector<Complex> > Cop;
  std::vector<std::vector<Complex> > Copss;
  for(size_t i=0; i<selOps.size(); i++){
    for(size_t j=0; j<selOps.size(); j++){
      const PDOperator &oi = optab.ops[optab.Find(selOps[i])];
      const PDOperator &oj = optab.ops[optab.Find(selOps[j])];
      bool sameBlock = ( optab.BlockOf(oi.name) == optab.BlockOf(oj.name) );
      if( !sameBlock && !doCross ) continue;
      std::vector<Complex> cc(T, Complex(0.0, 0.0));
      std::vector<Complex> ccss(T, Complex(0.0, 0.0));
      bool complete = true;
      for(size_t ci=0; ci<oi.comp.size() && complete; ci++){
        for(size_t cj=0; cj<oj.comp.size() && complete; cj++){
          int p = terms.Find(oi.comp[ci], oj.comp[cj]);
          int k = -1;
          for(size_t kk=0; kk<pairs.size(); kk++){
            if( pairs[kk] == p ) k = (int)kk;
          }
          if( k < 0 ){
            assert( !sameBlock && "a needed in-block pair was not computed (internal)" );
            complete = false;
            break;
          }
          RealD wgt = oi.coeff[ci] * oj.coeff[cj];   // real coefficients: conj is trivial
          for(int t=0; t<T; t++){
            cc[t]   += wgt * Cel[k][t];
            ccss[t] += wgt * Celss[k][t];
          }
        }
      }
      if( !complete ) continue;
      copNames.push_back(oi.name + "_" + oj.name);
      Cop.push_back(cc);
      Copss.push_back(ccss);
      std::cout << GridLogMessage << "Cop " << oi.name << " x " << oj.name
                << (sameBlock ? " (block " : " (CROSS ") << oi.JP << "/" << oj.JP << ")"
                << "  C(1) = " << cc[1] << "  C(2) = " << cc[2] << std::endl;
    }
  }

  // ------------------------------------------------------------------
  // HDF5 output (boss only).
  // ------------------------------------------------------------------
  std::unique_ptr<Hdf5Writer> WR;
  if( UGrid->IsBoss() ) WR.reset(new Hdf5Writer(outFile));

  BvarMeta meta;
  meta.config         = rec0.config;
  meta.mass           = rec0.mass;
  meta.M5             = rec0.M5;
  meta.b              = rec0.b;
  meta.c              = rec0.c;
  meta.Ls             = rec0.Ls;
  meta.T              = T;
  meta.nCorner        = nCorner;
  meta.smearWidth     = rec0.smearWidth;
  meta.smearNiter     = rec0.smearNiter;
  meta.sinkSmearWidth = doSinkSmear ? sinkSmearWidth : 0.0;
  meta.sinkSmearNiter = doSinkSmear ? sinkSmearNiter : 0;
  meta.termsFile      = termsFile;
  meta.opsFile        = opsFile;
  meta.pairMode       = pairMode;
  {
    std::vector<std::string> names, jps, defs, plist;
    for(size_t i=0; i<selOps.size(); i++){
      const PDOperator &o = optab.ops[optab.Find(selOps[i])];
      names.push_back(o.name);
      jps.push_back(o.JP);
      std::string d = o.name + ":";
      for(size_t ci=0; ci<o.comp.size(); ci++){
        if( ci > 0 ) d += ";";
        std::stringstream ss;
        ss << o.comp[ci] << "=" << std::setprecision(17) << o.coeff[ci];
        d += ss.str();
      }
      defs.push_back(d);
    }
    for(size_t k=0; k<pairs.size(); k++){
      plist.push_back(terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]]);
    }
    meta.opNames  = JoinStrings(names, ",");
    meta.opJP     = JoinStrings(jps, ",");
    meta.opDef    = JoinStrings(defs, "|");
    meta.pairList = JoinStrings(plist, ",");
  }
  if( WR ) write(*WR, "meta", meta);

  for(size_t k=0; k<pairs.size(); k++){
    CorrFile cf;
    cf.data = Cel[k];
    std::string name = "Cel_" + terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]];
    if( WR ) write(*WR, name, cf);
    if( doSinkSmear ){
      CorrFile cs;
      cs.data = Celss[k];
      if( WR ) write(*WR, "Celss_" + terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]], cs);
    }
  }
  for(size_t i=0; i<copNames.size(); i++){
    CorrFile cf;
    cf.data = Cop[i];
    if( WR ) write(*WR, "Cop_" + copNames[i], cf);
    if( doSinkSmear ){
      CorrFile cs;
      cs.data = Copss[i];
      if( WR ) write(*WR, "Copss_" + copNames[i], cs);
    }
  }
  if( doNaive ){
    std::cout << GridLogMessage << "naive-check summary: " << (naiveOK ? "PASSED" : "FAILED") << std::endl;
  }
  std::cout << GridLogMessage << "wrote " << outFile << ": meta + " << pairs.size() << " Cel + "
            << copNames.size() << " Cop datasets" << (doSinkSmear ? " (+ smeared-sink copies)" : "") << std::endl;

  Grid_finalize();
}
