/*
 * baryon_variants_mom_corr_claude.cc
 *
 * Copy of baryon_variants_corr_claude.cc (production, unchanged there) plus MOMENTUM-PROJECTED
 * correlators of A. S. Meyer's (LLNL) cubic / little-group irrep operators (private
 * communication 2026-09-28; converted by aaron_ops_convert_claude.py into
 * baryon_mom_ops_claude.txt). Plan: baryon_variants_mom_impl_plan_claude.md.
 *
 *   C_{AA'}(p,t) = sum_x e^{-i p.(x-y)} < B_A(x,t) B^\dagger_{A'}(y) >
 *                = e^{+i p.y} FFT_3d[ d_{AA'} ](p,t)          (Grid FFT::forward = e^{-ikx})
 *   C_{ij}(p,t)  = sum_{A,A'} c^i_A(p) conj(c^j_{A'}(p)) C_{AA'}(p,t)
 *
 * d_{AA'}(x) is the site density of PDTermTable::ContractPair, y the source position of the
 * dump. In flight every pair (A, A') is needed (parity mixes), so --momops requires the
 * all-pairs term file baryon_variants_terms_all_claude.txt. C_{ij} is formed per group
 * (frame, irrep, component) and averaged over the components of each (frame, irrep).
 *
 * Extra CLI (momentum path):
 *   --momops <file>      operator groups (baryon_mom_ops_claude.txt); enables the momentum path
 *   --mom-raw            also write the per-component correlators
 *   --no-p0              do not write the legacy p = 0 Cel_/Cop_ datasets (used when the
 *                        production bvar.all.<idx>.h5 already exists)
 *   --phase-check <n>    corner 0, point sink: compare the FFT projection with an explicit
 *                        phase x sliceSum at all momenta for the first n momentum pairs
 * Extra HDF5 datasets:
 *   mom_meta, Cmom_<frame>_<irrep>_<uid_i>_<uid_j> (component average), Cmomss_* (smeared
 *   sink), with --mom-raw also Cmomraw_<frame>_<irrep>_c<comp>_<uid_i>_<uid_j> and Cmomrawss_*.
 * The FFT host copy needs a single MPI rank (--mpi 1.1.1.1, as in production).
 *
 * ---- production header (baryon_variants_corr_claude.cc) ----
 *
 * Single-baryon two-point functions of the SU(Nc=4), one-flavour SDM B-form operators
 * (the 9 highest-weight |J^P,(n_+,n_-),J,M=J> operators of baryon_theory_claude.md
 * Sec. 4.1, or any state of the 35-state table) from the full Pauli-Dirac propagator
 * dump of point2all_prop_dumper_full_claude.cc.
 *
 *   C_{AA'}(t) = sum_x < B_A(x,t) B^\dagger_{A'}(0) >
 *              = P(A') sum_{a,b} \epsilon_a \epsilon_b det_{ij}[ G^{a_i b_j}_{A_i A'_j}(x,0) ]
 *   C_{OO'}(t) = sum_{A,A'} c^O_A conj(c^{O'}_{A'}) C_{AA'}(t)
 *
 * Term tables (baryon_variants_terms_claude.txt) and operator coefficients
 * (baryon_variants_ops_claude.txt / _all_) are text files generated by the Python
 * scripts; see baryon_variants_impl_plan_claude.md. Contraction kernel, readers and the
 * naive reference live in baryon_pd_common_claude.h.
 *
 * CLI:
 *   --src <file.pdfull.lime>      propagator dump (default ColdConfig.pdfull.lime)
 *   --out <file.h5>               output (default ColdConfig.bvar.h5)
 *   --terms <file>                term tables (default baryon_variants_terms_claude.txt)
 *   --ops <file>                  operator tables (default baryon_variants_ops_claude.txt)
 *   --op <name> | all             operator whose J^P block is computed (default all)
 *   --pairs block | sector | all  elementary pairs to compute and store (default block):
 *                                   block  = the pairs the selected block(s) need
 *                                   sector = every pair of the term file in the same
 *                                            (parity, J_3 mod 4) sector(s)
 *                                   all    = every pair of the term file
 *   --naive-check <nsample>       compare the kernel density with the naive Wick-form
 *                                 loop at nsample sites (0 = all sites) on corner 0
 *   --kernel-mode 0|1             site kernel variant (0 = gather sub-elements from the
 *                                 view [default], 1 = read the whole site object); both
 *                                 validated, identical results
 *   --cross                       also form C_{OO'} for operator pairs from DIFFERENT
 *                                 blocks whose elementary pairs are available
 *                                 (validation only: they vanish on the free field)
 *   --config <nersc>              gauge config, only needed for --sink-smear
 *   --sink-smear <w> <N>          also compute with a covariant Gaussian smeared sink
 *   --grid / --mpi                Grid layout
 *
 * HDF5 datasets (CorrFile = vector<Complex> of length T, compound (re,im)):
 *   meta, Cel_<A>_<A'> (corner average), Cop_<O>_<O'> (all pairs of each computed
 *   block); with --sink-smear also Celss_*, Copss_*.
 */

#include <Grid/Grid.h>
#include <algorithm>
#include <vector>
#include <sstream>
#include <memory>
#include <set>
#include <map>
#include <iomanip>
#include <fstream>

#include "baryon_pd_common_claude.h"

using namespace std;
using namespace Grid;

// Run metadata written alongside the correlators.
class BvarMeta: Serializable {
public:
  GRID_SERIALIZABLE_CLASS_MEMBERS(BvarMeta,
    std::string,         config,
    double,              mass,
    double,              M5,
    double,              b,
    double,              c,
    int,                 Ls,
    int,                 T,
    int,                 nCorner,
    double,              smearWidth,
    int,                 smearNiter,
    double,              sinkSmearWidth,
    int,                 sinkSmearNiter,
    std::string,         termsFile,
    std::string,         opsFile,
    std::string,         pairMode,
    std::string,         opNames,      // comma-joined
    std::string,         opJP,         // comma-joined, same order
    std::string,         opDef,        // per op "name:A=c;A=c", joined by "|"
    std::string,         pairList);    // comma-joined "A_A'"
};

// 2 J_3 = (n_0 + n_2) - (n_1 + n_3) of a tuple string.
static int J3TwiceOf(const std::string &tuple)
{
  int up = 0;
  int down = 0;
  for(size_t i=0; i<tuple.size(); i++){
    int d = tuple[i] - '0';
    if( d % 2 == 0 ) up++;
    else down++;
  }
  return up - down;
}

static bool SameSector(const std::string &a, const std::string &b)
{
  if( PDTermTable::ParityOf(a) != PDTermTable::ParityOf(b) ) return false;
  int d = J3TwiceOf(a) - J3TwiceOf(b);
  if( d < 0 ) d = -d;
  if( (d % 8) != 0 ) return false;
  return true;
}

static std::string JoinStrings(const std::vector<std::string> &v, const std::string &sep)
{
  std::string out;
  for(size_t i=0; i<v.size(); i++){
    if( i > 0 ) out += sep;
    out += v[i];
  }
  return out;
}

// --------------------------------------------------------------------------
// Momentum path
// --------------------------------------------------------------------------

// Metadata of the momentum datasets.
class MomMeta: Serializable {
public:
  GRID_SERIALIZABLE_CLASS_MEMBERS(MomMeta,
    std::string,         momOpsFile,
    int,                 nmom,
    std::string,         momList,      // "k:px,py,pz" joined by "|"
    std::string,         classList,    // "<frame>_<irrep>:<ncomp>:<uid>,<uid>,..." joined by "|"
    int,                 raw,
    int,                 p0Written);
};

struct MomOp {
  std::string               uid;
  std::vector<std::string>  comp;   // A of each component
  std::vector<ComplexD>     coeff;  // c_A, same order
};

struct MomGroup {
  std::string         frame;
  std::string         irrep;
  std::string         comp;   // component label of the file name (row x direction)
  int                 k;      // momentum index
  std::vector<MomOp>  ops;
};

// Operator groups of baryon_mom_ops_claude.txt; classes = (frame, irrep), each with the list
// of its groups (components) and its operator IDs (same in every component, same order).
class PDMomOperatorTable {
public:
  std::vector<std::vector<int> >  mom;          // integer momenta (units 2 pi / L)
  std::vector<MomGroup>           groups;
  std::vector<std::string>        className;    // "<frame>_<irrep>"
  std::vector<std::vector<int> >  classGroups;  // per class: group indices
  std::string                     fname;

  void Read(const std::string &file)
  {
    fname = file;
    std::ifstream in(file);
    assert( in.good() && "cannot open momentum operator table file" );
    std::string line;
    int nmom = -1;
    int ngroup = -1;
    int opsLeft = 0;
    int compLeft = 0;
    while( std::getline(in, line) ){
      if( line.empty() ) continue;
      if( line[0] == '#' ) continue;
      std::stringstream ss(line);
      std::string key;
      ss >> key;
      if( key == "nmom" ){
        ss >> nmom;
        continue;
      }
      if( key == "mom" ){
        int k;
        std::vector<int> p(3);
        ss >> k >> p[0] >> p[1] >> p[2];
        assert( k == (int)mom.size() && "momentum indices must be consecutive" );
        mom.push_back(p);
        continue;
      }
      if( key == "ngroup" ){
        ss >> ngroup;
        continue;
      }
      if( key == "group" ){
        assert( opsLeft == 0 && compLeft == 0 && "previous group is incomplete" );
        MomGroup g;
        int nops;
        ss >> g.frame >> g.irrep >> g.comp >> g.k >> nops;
        groups.push_back(g);
        opsLeft = nops;
        continue;
      }
      if( key == "op" ){
        assert( opsLeft > 0 && compLeft == 0 && "unexpected op line" );
        MomOp op;
        int ncomp;
        ss >> op.uid >> ncomp;
        groups.back().ops.push_back(op);
        opsLeft--;
        compLeft = ncomp;
        continue;
      }
      // component line: <A> <re> <im>
      assert( compLeft > 0 && "unexpected component line" );
      RealD re;
      RealD im;
      ss >> re >> im;
      groups.back().ops.back().comp.push_back(key);
      groups.back().ops.back().coeff.push_back(ComplexD(re, im));
      compLeft--;
    }
    assert( opsLeft == 0 && compLeft == 0 && "last group is incomplete" );
    assert( nmom == (int)mom.size() && "nmom does not match the mom lines" );
    assert( ngroup == (int)groups.size() && "ngroup does not match the group lines" );

    // classes (frame, irrep), in order of first appearance
    for(int g=0; g<(int)groups.size(); g++){
      std::string name = groups[g].frame + "_" + groups[g].irrep;
      int c = -1;
      for(int i=0; i<(int)className.size(); i++){
        if( className[i] == name ) c = i;
      }
      if( c < 0 ){
        className.push_back(name);
        classGroups.push_back(std::vector<int>());
        c = (int)className.size() - 1;
      }
      classGroups[c].push_back(g);
    }
    // every component of a class carries the same operator IDs in the same order
    for(size_t c=0; c<className.size(); c++){
      const MomGroup &g0 = groups[classGroups[c][0]];
      for(size_t i=1; i<classGroups[c].size(); i++){
        const MomGroup &gi = groups[classGroups[c][i]];
        assert( gi.ops.size() == g0.ops.size() && "components of a class differ in operator count" );
        for(size_t o=0; o<gi.ops.size(); o++){
          assert( gi.ops[o].uid == g0.ops[o].uid && "components of a class differ in operator IDs" );
        }
      }
    }
  }

  int NumOps(int c) const
  {
    return (int)groups[classGroups[c][0]].ops.size();
  }

  const std::string &Uid(int c, int i) const
  {
    return groups[classGroups[c][0]].ops[i].uid;
  }
};

// Spatial-FFT momentum projection of a site density onto a fixed list of momenta.
//   acc[k*T + t] += e^{+i p_k.y} sum_x e^{-i p_k.x} dens(x,t)
// FFT::forward = sum_x e^{-i k x} (unnormalised), then a host copy of the transformed field
// in lexicographic order (single MPI rank) and a pick of the nmom x T sites.
class MomProjector {
public:
  GridCartesian                   *grid;
  Coordinate                      latt;
  int                             T;
  std::vector<std::vector<int> >  mom;
  std::vector<long>               lexSite;    // [k*T + t]: lex index of the FFT site of p_k at t
  std::vector<ComplexD>           srcPhase;   // [k]: e^{+i p_k.y}
  std::unique_ptr<FFT>            fft;
  LatticeComplex                  ft;
  std::vector<LatticeComplex::scalar_object> host;

  MomProjector(GridCartesian *g, const std::vector<std::vector<int> > &moms)
    : grid(g), ft(g)
  {
    assert( grid->ProcessorCount() == 1 && "the momentum projection needs a single MPI rank" );
    latt = grid->FullDimensions();
    T = latt[Tdir];
    mom = moms;
    int nmom = (int)mom.size();
    lexSite.resize(nmom * T);
    for(int k=0; k<nmom; k++){
      Coordinate x(Nd, 0);
      for(int mu=0; mu<3; mu++){
        int L = latt[mu];
        x[mu] = ((mom[k][mu] % L) + L) % L;
      }
      for(int t=0; t<T; t++){
        x[Tdir] = t;
        int lex;
        Lexicographic::IndexFromCoor(x, lex, latt);
        lexSite[k*T + t] = lex;
      }
    }
    srcPhase.assign(nmom, ComplexD(1.0, 0.0));
    fft.reset(new FFT(grid));
  }

  void SetSource(const std::vector<int> &y)
  {
    for(size_t k=0; k<mom.size(); k++){
      RealD ph = 0.0;
      for(int mu=0; mu<3; mu++){
        ph += 2.0 * M_PI * mom[k][mu] * y[mu] / (RealD)latt[mu];
      }
      srcPhase[k] = ComplexD(cos(ph), sin(ph));
    }
  }

  // out[k*T + t] = e^{+i p_k.y} FFT[dens](p_k, t)   (overwritten, not accumulated)
  void Project(const LatticeComplex &dens, std::vector<ComplexD> &out)
  {
    Coordinate mask({1,1,1,0});
    fft->FFT_dim_mask(ft, dens, mask, FFT::forward);
    unvectorizeToLexOrdArray(host, ft);
    int nmom = (int)mom.size();
    out.resize(nmom * T);
    for(int k=0; k<nmom; k++){
      for(int t=0; t<T; t++){
        ComplexD v = TensorRemove(host[lexSite[k*T + t]]);
        out[k*T + t] = srcPhase[k] * v;
      }
    }
  }
};

// Contract all selected pairs of one propagator and accumulate the time-slice sums.
static void ContractAll(PDTermTable &terms, const std::vector<int> &pairs,
                        const LatticePropagator &G, int T,
                        std::vector<std::vector<Complex> > &Cel)
{
  LatticeComplex dens(G.Grid());
  std::vector<TComplex> sl;
  for(size_t k=0; k<pairs.size(); k++){
    int p = pairs[k];
    double t0 = usecond();
    terms.ContractPair(G, p, dens);
    sliceSum(dens, sl, Tdir);
    double t1 = usecond();
    for(int t=0; t<T; t++){
      Cel[k][t] += TensorRemove(sl[t]);
    }
    std::cout << GridLogMessage << "  pair " << terms.A[p] << " " << terms.Ap[p]
              << " (" << terms.nterm[p] << " terms) " << (t1 - t0) / 1.0e6 << " s"
              << "  C(0) = " << TensorRemove(sl[0]) << std::endl;
  }
}

// Momentum path: contract every pair of 'pairs' once and
//   - legacySlot[k] >= 0: accumulate the time-slice sum into Cel[legacySlot[k]] (p = 0, as ContractAll)
//   - momSlot[k]    >= 0: accumulate the momentum projection into Cmom[momSlot[k]][kk*T + t]
// For every projected pair the FFT at p = 0 (momentum index k0, if present) is compared with
// sliceSum; the largest relative difference is returned in maxP0.
static void ContractAllMom(PDTermTable &terms, const std::vector<int> &pairs,
                           const std::vector<int> &legacySlot, const std::vector<int> &momSlot,
                           MomProjector &proj, int k0, const LatticePropagator &G, int T,
                           std::vector<std::vector<Complex> > &Cel,
                           std::vector<std::vector<ComplexD> > &Cmom, RealD &maxP0)
{
  LatticeComplex dens(G.Grid());
  std::vector<TComplex> sl;
  std::vector<ComplexD> pm;
  double tKernel = 0.0;
  double tProj = 0.0;
  double tStart = usecond();
  for(size_t k=0; k<pairs.size(); k++){
    int p = pairs[k];
    double t0 = usecond();
    terms.ContractPair(G, p, dens);
    sliceSum(dens, sl, Tdir);
    double t1 = usecond();
    tKernel += t1 - t0;
    if( legacySlot[k] >= 0 ){
      for(int t=0; t<T; t++){
        Cel[legacySlot[k]][t] += TensorRemove(sl[t]);
      }
    }
    if( momSlot[k] >= 0 ){
      proj.Project(dens, pm);
      std::vector<ComplexD> &acc = Cmom[momSlot[k]];
      for(size_t i=0; i<pm.size(); i++){
        acc[i] += pm[i];
      }
      if( k0 >= 0 ){
        // ORIGINAL (per-entry scale; meaningless for pairs that vanish at p = 0 by parity):
        // RealD scale = std::max(1.0e-30, (RealD)abs(ref));
        // scale = the largest |C_{AA'}(p,t)| of this pair over all momenta and t
        RealD scale = 1.0e-300;
        for(size_t i=0; i<pm.size(); i++){
          scale = std::max(scale, (RealD)abs(pm[i]));
        }
        for(int t=0; t<T; t++){
          ComplexD ref = TensorRemove(sl[t]);
          RealD rel = abs(pm[k0*T + t] - ref) / scale;
          if( rel > maxP0 ) maxP0 = rel;
        }
      }
    }
    double t2 = usecond();
    tProj += t2 - t1;
    if( k < 3 || (k + 1) % 200 == 0 || k + 1 == pairs.size() ){
      std::cout << GridLogMessage << "  pair " << k + 1 << "/" << pairs.size() << " " << terms.A[p] << " "
                << terms.Ap[p] << " (" << terms.nterm[p] << " terms)  C(0) = " << TensorRemove(sl[0])
                << "  elapsed " << (t2 - tStart) / 1.0e6 << " s" << std::endl;
    }
  }
  std::cout << GridLogMessage << "  contraction+sliceSum " << tKernel / 1.0e6 << " s, FFT+projection "
            << tProj / 1.0e6 << " s, max rel |FFT(p=0) - sliceSum| = " << maxP0 << std::endl;
}

// Explicit check of the FFT projection: for the first npair projected pairs, at every momentum,
// sum_x e^{-i p.(x-y)} dens(x) by a phase field and sliceSum vs MomProjector::Project.
static RealD PhaseCheck(PDTermTable &terms, const std::vector<int> &pairs, const std::vector<int> &momSlot,
                        MomProjector &proj, const std::vector<int> &y, const LatticePropagator &G,
                        int T, int npair)
{
  GridBase *grid = G.Grid();
  LatticeComplex dens(grid);
  LatticeComplex coor(grid);
  LatticeComplex phase(grid);
  LatticeComplex tmp(grid);
  ComplexD ci(0.0, 1.0);
  std::vector<TComplex> sl;
  std::vector<ComplexD> pm;
  RealD worst = 0.0;
  int done = 0;
  for(size_t k=0; k<pairs.size() && done < npair; k++){
    if( momSlot[k] < 0 ) continue;
    int p = pairs[k];
    terms.ContractPair(G, p, dens);
    proj.Project(dens, pm);
    RealD pworst = 0.0;
    // scale = the largest |FFT value| of this pair over all momenta and t (per-entry scales
    // are meaningless where C vanishes by symmetry)
    RealD scale = 1.0e-300;
    for(size_t i=0; i<pm.size(); i++){
      scale = std::max(scale, (RealD)abs(pm[i]));
    }
    for(size_t km=0; km<proj.mom.size(); km++){
      phase = Zero();
      for(int mu=0; mu<3; mu++){
        RealD twoPiL = 2.0 * M_PI / (RealD)proj.latt[mu];
        LatticeCoordinate(coor, mu);
        phase = phase + (twoPiL * (proj.mom[km][mu])) * coor;
      }
      phase = exp(phase * (-ci));
      tmp = phase * dens;
      sliceSum(tmp, sl, Tdir);
      // source factor e^{+i p.y}, computed independently of proj.srcPhase
      RealD py = 0.0;
      for(int mu=0; mu<3; mu++){
        py += 2.0 * M_PI * proj.mom[km][mu] * y[mu] / (RealD)proj.latt[mu];
      }
      ComplexD sph(cos(py), sin(py));
      for(int t=0; t<T; t++){
        ComplexD ref = sph * TensorRemove(sl[t]);
        // ORIGINAL: RealD scale = std::max(1.0e-30, (RealD)abs(ref));
        RealD rel = abs(pm[km*T + t] - ref) / scale;
        if( rel > pworst ) pworst = rel;
      }
    }
    std::cout << GridLogMessage << "  phase-check pair " << terms.A[p] << " " << terms.Ap[p]
              << ": max rel |FFT - phase sliceSum| over " << proj.mom.size() << " momenta = " << pworst << std::endl;
    if( pworst > worst ) worst = pworst;
    done++;
  }
  return worst;
}

// Operator correlators of one group: C_{ij}[(i*nops + j)*T + t]
//   = sum_{A in O_i, A' in O_j} c^i_A conj(c^j_{A'}) Cmom[slot(A,A')][k*T + t]
static void GroupCorrelators(const MomGroup &g, const std::map<std::pair<std::string,std::string>,int> &slotOf,
                             const std::vector<std::vector<ComplexD> > &Cmom, int T,
                             std::vector<ComplexD> &out)
{
  int nops = (int)g.ops.size();
  out.assign(nops * nops * T, ComplexD(0.0, 0.0));
  for(int i=0; i<nops; i++){
    const MomOp &oi = g.ops[i];
    for(int j=0; j<nops; j++){
      const MomOp &oj = g.ops[j];
      ComplexD *dst = &out[(i*nops + j) * T];
      for(size_t a=0; a<oi.comp.size(); a++){
        for(size_t b=0; b<oj.comp.size(); b++){
          std::map<std::pair<std::string,std::string>,int>::const_iterator it =
            slotOf.find(std::make_pair(oi.comp[a], oj.comp[b]));
          assert( it != slotOf.end() && "a pair needed by a momentum operator was not projected" );
          const ComplexD *src = &Cmom[it->second][g.k * T];
          ComplexD wgt = oi.coeff[a] * conj(oj.coeff[b]);
          for(int t=0; t<T; t++){
            dst[t] += wgt * src[t];
          }
        }
      }
    }
  }
}

// Host evaluation of the det form for one site from the term table (independent of the
// device kernel): sum_terms w * Det4(G[rows, cols]).
static Complex HostTableDensity(const PDTermTable &terms, int p, const SpinColourMatrix &Gs)
{
  Complex val(0.0, 0.0);
  for(int k=0; k<terms.nterm[p]; k++){
    const int *t = &terms.idx[0] + 8 * (terms.offset[p] + k);
    Complex M[16];
    for(int i=0; i<4; i++){
      int sr = t[i] / Nc;
      int cr = t[i] % Nc;
      for(int j=0; j<4; j++){
        int sc = t[4+j] / Nc;
        int cc = t[4+j] % Nc;
        M[4*i+j] = Gs()(sr,sc)(cr,cc);
      }
    }
    val = val + Complex(terms.w[terms.offset[p] + k], 0.0) * Det4(M);
  }
  return val;
}

// Naive check: kernel density vs (i) the host det-form sum over the same term table and
// (ii) the naive Wick-form host loop, at sampled sites. Reports the worst site per pair.
static bool NaiveCheck(PDTermTable &terms, const std::vector<int> &pairs,
                       const LatticePropagator &G, int nsample)
{
  GridBase *grid = G.Grid();
  Coordinate latt = grid->FullDimensions();
  long vol = 1;
  for(int mu=0; mu<Nd; mu++) vol *= latt[mu];
  long stride = 1;
  if( nsample > 0 ){
    stride = vol / nsample;
    if( stride < 1 ) stride = 1;
  }
  PDNaive naive;
  LatticeComplex dens(grid);
  RealD maxKH = 0.0;   // kernel vs host det form
  RealD maxHN = 0.0;   // host det form vs naive
  long nchecked = 0;
  for(size_t k=0; k<pairs.size(); k++){
    int p = pairs[k];
    terms.ContractPair(G, p, dens);
    RealD pKH = 0.0;
    RealD pHN = 0.0;
    Coordinate worst(Nd, 0);
    Complex wk, wh, wn;
    for(long site=0; site<vol; site+=stride){
      Coordinate coor(Nd);
      Lexicographic::CoorFromIndex(coor, site, latt);
      SpinColourMatrix Gs;
      peekSite(Gs, G, coor);
      TComplex dv;
      peekSite(dv, dens, coor);
      Complex kern = TensorRemove(dv);
      Complex host = HostTableDensity(terms, p, Gs);
      Complex ref  = naive.SiteDensity(Gs, terms.A[p], terms.Ap[p]);
      RealD scale = std::max(1.0e-30, abs(ref));
      RealD rKH = abs(kern - host) / scale;
      RealD rHN = abs(host - ref) / scale;
      if( rKH > pKH ){
        pKH = rKH;
        worst = coor;
        wk = kern;
        wh = host;
        wn = ref;
      }
      pHN = std::max(pHN, rHN);
      nchecked++;
    }
    maxKH = std::max(maxKH, pKH);
    maxHN = std::max(maxHN, pHN);
    std::cout << GridLogMessage << "  naive-check pair " << terms.A[p] << " " << terms.Ap[p]
              << " rel(kernel,hostdet) = " << pKH << " rel(hostdet,naive) = " << pHN
              << " worst site (" << worst[0] << "," << worst[1] << "," << worst[2] << "," << worst[3]
              << ") kernel " << wk << " hostdet " << wh << " naive " << wn << std::endl;
  }
  std::cout << GridLogMessage << "naive-check: " << nchecked << " site evaluations, max rel(kernel,hostdet) = "
            << maxKH << ", max rel(hostdet,naive) = " << maxHN << std::endl;
  bool ok = ( maxKH < 1.0e-10 && maxHN < 1.0e-10 );
  if( ok ) std::cout << GridLogMessage << "naive-check PASSED." << std::endl;
  else     std::cout << GridLogMessage << "naive-check FAILED (continuing for diagnostics)." << std::endl;
  return ok;
}

int main(int argc, char ** argv)
{
  Grid_init(&argc, &argv);

  Coordinate latt        = GridDefaultLatt();
  Coordinate simd_layout = GridDefaultSimd(Nd, vComplex::Nsimd());
  Coordinate mpi_layout  = GridDefaultMpi();
  GridCartesian * UGrid  = SpaceTimeGrid::makeFourDimGrid(latt, simd_layout, mpi_layout);
  GridCartesian * UGridF = SpaceTimeGrid::makeFourDimGrid(latt, GridDefaultSimd(Nd, vComplexF::Nsimd()), mpi_layout);
  const int T = latt[Tdir];

  // ------------------------------------------------------------------
  // CLI
  // ------------------------------------------------------------------
  std::string srcFile   = "ColdConfig.pdfull.lime";
  std::string outFile   = "ColdConfig.bvar.h5";
  std::string termsFile = "baryon_variants_terms_claude.txt";
  std::string opsFile   = "baryon_variants_ops_claude.txt";
  std::string opName    = "all";
  std::string pairMode  = "block";
  std::string configFile;
  bool  doNaive     = false;
  int   naiveSample = 0;
  bool  doCross     = false;
  bool  naiveOK     = true;
  int   kernelMode  = 0;
  bool  doSinkSmear = false;
  RealD sinkSmearWidth = 0.0;
  int   sinkSmearNiter = 0;
  std::string momOpsFile;
  bool  doMom      = false;
  bool  momRaw     = false;
  bool  noP0       = false;
  int   phaseCheck = 0;
  for(int i=0; i<argc; i++){
    std::string a(argv[i]);
    if( a == "--momops" ){
      momOpsFile = argv[i+1];
      doMom = true;
    }
    if( a == "--mom-raw" )     momRaw = true;
    if( a == "--no-p0" )       noP0 = true;
    if( a == "--phase-check" ) phaseCheck = std::stoi(argv[i+1]);
    if( a == "--src" )    srcFile   = argv[i+1];
    if( a == "--out" )    outFile   = argv[i+1];
    if( a == "--terms" )  termsFile = argv[i+1];
    if( a == "--ops" )    opsFile   = argv[i+1];
    if( a == "--op" )     opName    = argv[i+1];
    if( a == "--pairs" )  pairMode  = argv[i+1];
    if( a == "--config" ) configFile = argv[i+1];
    if( a == "--cross" )  doCross = true;
    if( a == "--kernel-mode" ) kernelMode = std::stoi(argv[i+1]);
    if( a == "--naive-check" ){
      doNaive = true;
      naiveSample = std::stoi(argv[i+1]);
    }
    if( a == "--sink-smear" ){
      sinkSmearWidth = stod(argv[i+1]);
      sinkSmearNiter = std::stoi(argv[i+2]);
      doSinkSmear = (sinkSmearWidth > 0.0 && sinkSmearNiter > 0);
    }
  }
  assert( (pairMode == "block" || pairMode == "sector" || pairMode == "all") && "--pairs must be block|sector|all" );
  std::cout << GridLogMessage << "src = " << srcFile << ", out = " << outFile << std::endl;
  std::cout << GridLogMessage << "terms = " << termsFile << ", ops = " << opsFile << std::endl;
  std::cout << GridLogMessage << "op = " << opName << ", pairs = " << pairMode << std::endl;
  std::cout << GridLogMessage << "momops = " << (doMom ? momOpsFile : std::string("(none)"))
            << ", mom-raw " << momRaw << ", no-p0 " << noP0 << ", phase-check " << phaseCheck << std::endl;
  assert( (doMom || !noP0) && "--no-p0 without --momops leaves nothing to compute" );

  // ------------------------------------------------------------------
  // Tables and operator / block selection.
  // ------------------------------------------------------------------
  PDTermTable terms;
  terms.Read(termsFile);
  PDOperatorTable optab;
  optab.Read(opsFile);

  std::vector<int> blocks;     // block indices to compute
  if( opName == "all" ){
    for(int b=0; b<(int)optab.blockJP.size(); b++) blocks.push_back(b);
  } else {
    int b = optab.BlockOf(opName);
    assert( b >= 0 && "--op name not found in the operator table blocks" );
    blocks.push_back(b);
  }
  std::vector<std::string> selOps;   // operators of the selected blocks (in block order)
  for(size_t ib=0; ib<blocks.size(); ib++){
    int b = blocks[ib];
    for(size_t i=0; i<optab.blockOps[b].size(); i++) selOps.push_back(optab.blockOps[b][i]);
  }
  std::cout << GridLogMessage << "computing " << blocks.size() << " block(s), operators: "
            << JoinStrings(selOps, ",") << std::endl;

  // Elementary pairs needed by the selected blocks (ordered (A, A') over all operator
  // pairs of each block), and the pairs to compute according to --pairs.
  std::set<std::pair<std::string,std::string> > needed;
  for(size_t ib=0; ib<blocks.size(); ib++){
    int b = blocks[ib];
    for(size_t i=0; i<optab.blockOps[b].size(); i++){
      for(size_t j=0; j<optab.blockOps[b].size(); j++){
        const PDOperator &oi = optab.ops[optab.Find(optab.blockOps[b][i])];
        const PDOperator &oj = optab.ops[optab.Find(optab.blockOps[b][j])];
        for(size_t ci=0; ci<oi.comp.size(); ci++){
          for(size_t cj=0; cj<oj.comp.size(); cj++){
            needed.insert(std::make_pair(oi.comp[ci], oj.comp[cj]));
          }
        }
      }
    }
  }
  std::vector<int> pairs;     // indices into terms
  for(int p=0; p<terms.NPairs(); p++){
    bool take = false;
    if( pairMode == "all" ){
      take = true;
    } else if( pairMode == "block" ){
      take = ( needed.count(std::make_pair(terms.A[p], terms.Ap[p])) > 0 );
    } else {
      // sector: same (parity, J_3 mod 4) as any component of the selected operators
      for(size_t i=0; i<selOps.size() && !take; i++){
        const PDOperator &o = optab.ops[optab.Find(selOps[i])];
        for(size_t ci=0; ci<o.comp.size() && !take; ci++){
          if( SameSector(terms.A[p], o.comp[ci]) && SameSector(terms.Ap[p], o.comp[ci]) ) take = true;
        }
      }
    }
    if( take ) pairs.push_back(p);
  }
  // every needed pair must be available
  std::set<std::pair<std::string,std::string> >::iterator it;
  for(it=needed.begin(); it!=needed.end(); ++it){
    int p = terms.Find(it->first, it->second);
    assert( p >= 0 && "a pair needed by the selected operators is missing from the term file" );
    bool present = false;
    for(size_t k=0; k<pairs.size(); k++){
      if( pairs[k] == p ) present = true;
    }
    assert( present && "a needed pair was not selected (internal)" );
  }
  std::cout << GridLogMessage << "elementary pairs to compute: " << pairs.size()
            << " (needed by the blocks: " << needed.size() << ")" << std::endl;
  if( noP0 ){
    blocks.clear();
    selOps.clear();
    pairs.clear();
    std::cout << GridLogMessage << "--no-p0: legacy p = 0 Cel_/Cop_ datasets are NOT computed" << std::endl;
  }

  // ------------------------------------------------------------------
  // Momentum path: operator groups, the pairs they need (slots), and the
  // combined compute list allPairs (legacy pairs + momentum pairs, each once).
  // ------------------------------------------------------------------
  PDMomOperatorTable momtab;
  std::map<std::pair<std::string,std::string>,int> slotOf;   // (A, A') -> momentum slot
  std::vector<int> momTermIdx;                               // slot -> term pair index
  int k0 = -1;
  if( doMom ){
    momtab.Read(momOpsFile);
    for(size_t k=0; k<momtab.mom.size(); k++){
      if( momtab.mom[k][0] == 0 && momtab.mom[k][1] == 0 && momtab.mom[k][2] == 0 ) k0 = (int)k;
    }
    for(size_t g=0; g<momtab.groups.size(); g++){
      const MomGroup &grp = momtab.groups[g];
      for(size_t i=0; i<grp.ops.size(); i++){
        for(size_t j=0; j<grp.ops.size(); j++){
          for(size_t a=0; a<grp.ops[i].comp.size(); a++){
            for(size_t b=0; b<grp.ops[j].comp.size(); b++){
              std::pair<std::string,std::string> key(grp.ops[i].comp[a], grp.ops[j].comp[b]);
              if( slotOf.count(key) > 0 ) continue;
              int p = terms.Find(key.first, key.second);
              assert( p >= 0 && "a pair needed by the momentum operators is missing from the term file (use baryon_variants_terms_all_claude.txt)" );
              slotOf[key] = (int)momTermIdx.size();
              momTermIdx.push_back(p);
            }
          }
        }
      }
    }
    std::cout << GridLogMessage << "momentum operators: " << momtab.groups.size() << " groups in "
              << momtab.className.size() << " (frame, irrep) classes, " << momtab.mom.size()
              << " momenta, " << momTermIdx.size() << " elementary pairs projected" << std::endl;
  }
  std::vector<int> allPairs;
  std::vector<int> legacySlot;
  std::vector<int> momSlot;
  {
    std::map<int,int> legacyOf;
    for(size_t k=0; k<pairs.size(); k++) legacyOf[pairs[k]] = (int)k;
    std::map<int,int> momOf;
    for(size_t s=0; s<momTermIdx.size(); s++) momOf[momTermIdx[s]] = (int)s;
    for(int p=0; p<terms.NPairs(); p++){
      int ls = -1;
      int ms = -1;
      if( legacyOf.count(p) > 0 ) ls = legacyOf[p];
      if( momOf.count(p) > 0 ) ms = momOf[p];
      if( ls < 0 && ms < 0 ) continue;
      allPairs.push_back(p);
      legacySlot.push_back(ls);
      momSlot.push_back(ms);
    }
  }
  if( doMom ){
    std::cout << GridLogMessage << "combined compute list: " << allPairs.size() << " pairs ("
              << pairs.size() << " legacy p = 0, " << momTermIdx.size() << " momentum)" << std::endl;
  }
  terms.Upload();
  terms.kernelMode = kernelMode;
  std::cout << GridLogMessage << "kernel mode " << kernelMode << " (0 = sub-element gather, 1 = whole site object)" << std::endl;

  // ------------------------------------------------------------------
  // Optional gauge field for sink smearing.
  // ------------------------------------------------------------------
  std::vector<LatticeColourMatrix> U(Nd, UGrid);
  if( doSinkSmear ){
    LatticeGaugeField Umu(UGrid);
    if( configFile.size() > 0 ){
      FieldMetaData header;
      NerscIO::readConfiguration(Umu, header, configFile);
      std::cout << GridLogMessage << "sink smearing with gauge config " << configFile << std::endl;
    } else {
      SU<Nc>::ColdConfiguration(Umu);
      std::cout << GridLogMessage << "sink smearing with COLD gauge field (no --config)" << std::endl;
    }
    SpatialLinks(Umu, U);
    std::cout << GridLogMessage << "sink smear: width " << sinkSmearWidth << " niter " << sinkSmearNiter << std::endl;
  }

  // ------------------------------------------------------------------
  // Corner loop: read one corner's 16 blocks, contract, accumulate.
  // ------------------------------------------------------------------
  std::vector<std::vector<Complex> > Cel(pairs.size(), std::vector<Complex>(T, Complex(0.0, 0.0)));
  std::vector<std::vector<Complex> > Celss(pairs.size(), std::vector<Complex>(T, Complex(0.0, 0.0)));
  int nmom = (int)momtab.mom.size();
  std::vector<std::vector<ComplexD> > Cmom(momTermIdx.size(), std::vector<ComplexD>(nmom * T, ComplexD(0.0, 0.0)));
  std::vector<std::vector<ComplexD> > Cmomss;
  if( doSinkSmear ) Cmomss = Cmom;
  std::unique_ptr<MomProjector> proj;
  if( doMom ) proj.reset(new MomProjector(UGrid, momtab.mom));
  RealD maxP0 = 0.0;
  RealD phaseWorst = -1.0;
  PropRecord rec0;
  int nCorner = 0;
  {
    LatticePropagator G(UGrid);
    int corner = 0;
    while( true ){
      PropRecord rec;
      double t0 = usecond();
      int seen = ReadPDFullCorner(srcFile, UGrid, UGridF, corner, G, rec);
      double t1 = usecond();
      if( corner == 0 ){
        rec0 = rec;
        nCorner = seen;
        std::cout << GridLogMessage << "dump has " << nCorner << " corner(s); config " << rec.config
                  << " mass " << rec.mass << " M5 " << rec.M5 << " smear w " << rec.smearWidth
                  << " N " << rec.smearNiter << std::endl;
      }
      std::cout << GridLogMessage << "=== corner " << corner << " (" << rec.srcCoord[0] << ","
                << rec.srcCoord[1] << "," << rec.srcCoord[2] << "," << rec.srcCoord[3]
                << ") read in " << (t1 - t0) / 1.0e6 << " s, norm2(G) = " << norm2(G) << std::endl;

      if( doNaive && corner == 0 ){
        // ORIGINAL: naiveOK = NaiveCheck(terms, pairs, G, naiveSample);
        if( pairs.size() > 0 ) naiveOK = NaiveCheck(terms, pairs, G, naiveSample);
        else                   naiveOK = NaiveCheck(terms, allPairs, G, naiveSample);
      }

      if( doMom ){
        proj->SetSource(rec.srcCoord);
        if( phaseCheck > 0 && corner == 0 ){
          phaseWorst = PhaseCheck(terms, allPairs, momSlot, *proj, rec.srcCoord, G, T, phaseCheck);
          std::cout << GridLogMessage << "phase-check: max rel |FFT - phase sliceSum| = " << phaseWorst << std::endl;
        }
      }

      std::cout << GridLogMessage << "point sink:" << std::endl;
      // ORIGINAL: ContractAll(terms, pairs, G, T, Cel);
      if( doMom ) ContractAllMom(terms, allPairs, legacySlot, momSlot, *proj, k0, G, T, Cel, Cmom, maxP0);
      else        ContractAll(terms, pairs, G, T, Cel);

      if( doSinkSmear ){
        LatticePropagator Gs(UGrid);
        Gs = G;
        CovariantSmearing<PeriodicGimplD>::GaussianSmear(U, Gs, sinkSmearWidth, sinkSmearNiter, Tdir);
        std::cout << GridLogMessage << "smeared sink:" << std::endl;
        // ORIGINAL: ContractAll(terms, pairs, Gs, T, Celss);
        if( doMom ) ContractAllMom(terms, allPairs, legacySlot, momSlot, *proj, k0, Gs, T, Celss, Cmomss, maxP0);
        else        ContractAll(terms, pairs, Gs, T, Celss);
      }

      corner++;
      if( corner >= nCorner ) break;
    }
  }
  for(size_t k=0; k<pairs.size(); k++){
    for(int t=0; t<T; t++){
      Cel[k][t]   = Cel[k][t]   / (RealD)nCorner;
      Celss[k][t] = Celss[k][t] / (RealD)nCorner;
    }
  }
  for(size_t s=0; s<Cmom.size(); s++){
    for(size_t i=0; i<Cmom[s].size(); i++){
      Cmom[s][i] = Cmom[s][i] / (RealD)nCorner;
      if( doSinkSmear ) Cmomss[s][i] = Cmomss[s][i] / (RealD)nCorner;
    }
  }

  // ------------------------------------------------------------------
  // Momentum operator correlators: per group, then averaged over the
  // components of each (frame, irrep) class. Cavg[c][(i*nops + j)*T + t].
  // ------------------------------------------------------------------
  std::vector<std::vector<ComplexD> > Cavg(momtab.className.size());
  std::vector<std::vector<ComplexD> > Cavgss(momtab.className.size());
  std::vector<std::vector<ComplexD> > Craw(momtab.groups.size());
  std::vector<std::vector<ComplexD> > Crawss(momtab.groups.size());
  if( doMom ){
    double t0 = usecond();
    for(size_t c=0; c<momtab.className.size(); c++){
      int nops = momtab.NumOps(c);
      int ncomp = (int)momtab.classGroups[c].size();
      Cavg[c].assign(nops * nops * T, ComplexD(0.0, 0.0));
      if( doSinkSmear ) Cavgss[c].assign(nops * nops * T, ComplexD(0.0, 0.0));
      for(int ig=0; ig<ncomp; ig++){
        int g = momtab.classGroups[c][ig];
        GroupCorrelators(momtab.groups[g], slotOf, Cmom, T, Craw[g]);
        for(size_t i=0; i<Craw[g].size(); i++){
          Cavg[c][i] += Craw[g][i] / (RealD)ncomp;
        }
        if( doSinkSmear ){
          GroupCorrelators(momtab.groups[g], slotOf, Cmomss, T, Crawss[g]);
          for(size_t i=0; i<Crawss[g].size(); i++){
            Cavgss[c][i] += Crawss[g][i] / (RealD)ncomp;
          }
        }
      }
      std::cout << GridLogMessage << "Cmom " << momtab.className[c] << ": " << nops << " ops x " << ncomp
                << " components, C_00(1) = " << Cavg[c][1] << std::endl;
    }
    double t1 = usecond();
    std::cout << GridLogMessage << "momentum operator correlators formed in " << (t1 - t0) / 1.0e6 << " s" << std::endl;
  }

  // ------------------------------------------------------------------
  // Operator correlators C_{OO'} for every ordered pair inside each computed block.
  // ------------------------------------------------------------------
  // Operator pairs: all ordered pairs inside each computed block; with --cross also
  // the pairs across blocks whose elementary pairs were computed (skipped otherwise).
  std::vector<std::string> copNames;
  std::vector<std::vector<Complex> > Cop;
  std::vector<std::vector<Complex> > Copss;
  for(size_t i=0; i<selOps.size(); i++){
    for(size_t j=0; j<selOps.size(); j++){
      const PDOperator &oi = optab.ops[optab.Find(selOps[i])];
      const PDOperator &oj = optab.ops[optab.Find(selOps[j])];
      bool sameBlock = ( optab.BlockOf(oi.name) == optab.BlockOf(oj.name) );
      if( !sameBlock && !doCross ) continue;
      std::vector<Complex> cc(T, Complex(0.0, 0.0));
      std::vector<Complex> ccss(T, Complex(0.0, 0.0));
      bool complete = true;
      for(size_t ci=0; ci<oi.comp.size() && complete; ci++){
        for(size_t cj=0; cj<oj.comp.size() && complete; cj++){
          int p = terms.Find(oi.comp[ci], oj.comp[cj]);
          int k = -1;
          for(size_t kk=0; kk<pairs.size(); kk++){
            if( pairs[kk] == p ) k = (int)kk;
          }
          if( k < 0 ){
            assert( !sameBlock && "a needed in-block pair was not computed (internal)" );
            complete = false;
            break;
          }
          RealD wgt = oi.coeff[ci] * oj.coeff[cj];   // real coefficients: conj is trivial
          for(int t=0; t<T; t++){
            cc[t]   += wgt * Cel[k][t];
            ccss[t] += wgt * Celss[k][t];
          }
        }
      }
      if( !complete ) continue;
      copNames.push_back(oi.name + "_" + oj.name);
      Cop.push_back(cc);
      Copss.push_back(ccss);
      std::cout << GridLogMessage << "Cop " << oi.name << " x " << oj.name
                << (sameBlock ? " (block " : " (CROSS ") << oi.JP << "/" << oj.JP << ")"
                << "  C(1) = " << cc[1] << "  C(2) = " << cc[2] << std::endl;
    }
  }

  // ------------------------------------------------------------------
  // HDF5 output (boss only).
  // ------------------------------------------------------------------
  std::unique_ptr<Hdf5Writer> WR;
  if( UGrid->IsBoss() ) WR.reset(new Hdf5Writer(outFile));

  BvarMeta meta;
  meta.config         = rec0.config;
  meta.mass           = rec0.mass;
  meta.M5             = rec0.M5;
  meta.b              = rec0.b;
  meta.c              = rec0.c;
  meta.Ls             = rec0.Ls;
  meta.T              = T;
  meta.nCorner        = nCorner;
  meta.smearWidth     = rec0.smearWidth;
  meta.smearNiter     = rec0.smearNiter;
  meta.sinkSmearWidth = doSinkSmear ? sinkSmearWidth : 0.0;
  meta.sinkSmearNiter = doSinkSmear ? sinkSmearNiter : 0;
  meta.termsFile      = termsFile;
  meta.opsFile        = opsFile;
  // ORIGINAL: meta.pairMode       = pairMode;
  meta.pairMode       = noP0 ? std::string("none (--no-p0)") : pairMode;
  {
    std::vector<std::string> names, jps, defs, plist;
    for(size_t i=0; i<selOps.size(); i++){
      const PDOperator &o = optab.ops[optab.Find(selOps[i])];
      names.push_back(o.name);
      jps.push_back(o.JP);
      std::string d = o.name + ":";
      for(size_t ci=0; ci<o.comp.size(); ci++){
        if( ci > 0 ) d += ";";
        std::stringstream ss;
        ss << o.comp[ci] << "=" << std::setprecision(17) << o.coeff[ci];
        d += ss.str();
      }
      defs.push_back(d);
    }
    for(size_t k=0; k<pairs.size(); k++){
      plist.push_back(terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]]);
    }
    meta.opNames  = JoinStrings(names, ",");
    meta.opJP     = JoinStrings(jps, ",");
    meta.opDef    = JoinStrings(defs, "|");
    meta.pairList = JoinStrings(plist, ",");
    // HDF5 rejects zero-length string attributes (H5Tset_size: size must be positive);
    // with --no-p0 the legacy lists are empty
    if( meta.opNames.empty() )  meta.opNames  = "none";
    if( meta.opJP.empty() )     meta.opJP     = "none";
    if( meta.opDef.empty() )    meta.opDef    = "none";
    if( meta.pairList.empty() ) meta.pairList = "none";
  }
  if( WR ) write(*WR, "meta", meta);

  // legacy p = 0 datasets: pairs / copNames are empty with --no-p0
  for(size_t k=0; k<pairs.size(); k++){
    CorrFile cf;
    cf.data = Cel[k];
    std::string name = "Cel_" + terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]];
    if( WR ) write(*WR, name, cf);
    if( doSinkSmear ){
      CorrFile cs;
      cs.data = Celss[k];
      if( WR ) write(*WR, "Celss_" + terms.A[pairs[k]] + "_" + terms.Ap[pairs[k]], cs);
    }
  }
  for(size_t i=0; i<copNames.size(); i++){
    CorrFile cf;
    cf.data = Cop[i];
    if( WR ) write(*WR, "Cop_" + copNames[i], cf);
    if( doSinkSmear ){
      CorrFile cs;
      cs.data = Copss[i];
      if( WR ) write(*WR, "Copss_" + copNames[i], cs);
    }
  }
  // momentum datasets
  int nMomWritten = 0;
  if( doMom ){
    MomMeta mm;
    mm.momOpsFile = momOpsFile;
    mm.nmom       = nmom;
    mm.raw        = momRaw ? 1 : 0;
    mm.p0Written  = noP0 ? 0 : 1;
    std::vector<std::string> ml;
    for(int k=0; k<nmom; k++){
      std::stringstream ss;
      ss << k << ":" << momtab.mom[k][0] << "," << momtab.mom[k][1] << "," << momtab.mom[k][2];
      ml.push_back(ss.str());
    }
    mm.momList = JoinStrings(ml, "|");
    std::vector<std::string> cl;
    for(size_t c=0; c<momtab.className.size(); c++){
      std::vector<std::string> uids;
      for(int i=0; i<momtab.NumOps(c); i++) uids.push_back(momtab.Uid(c, i));
      std::stringstream ss;
      ss << momtab.className[c] << ":" << momtab.classGroups[c].size() << ":" << JoinStrings(uids, ",");
      cl.push_back(ss.str());
    }
    mm.classList = JoinStrings(cl, "|");
    if( WR ) write(*WR, "mom_meta", mm);

    for(size_t c=0; c<momtab.className.size(); c++){
      int nops = momtab.NumOps(c);
      for(int i=0; i<nops; i++){
        for(int j=0; j<nops; j++){
          std::string tag = momtab.className[c] + "_" + momtab.Uid(c, i) + "_" + momtab.Uid(c, j);
          CorrFile cf;
          cf.data.assign(Cavg[c].begin() + (i*nops + j) * T, Cavg[c].begin() + (i*nops + j + 1) * T);
          if( WR ) write(*WR, "Cmom_" + tag, cf);
          nMomWritten++;
          if( doSinkSmear ){
            CorrFile cs;
            cs.data.assign(Cavgss[c].begin() + (i*nops + j) * T, Cavgss[c].begin() + (i*nops + j + 1) * T);
            if( WR ) write(*WR, "Cmomss_" + tag, cs);
          }
        }
      }
    }
    if( momRaw ){
      for(size_t g=0; g<momtab.groups.size(); g++){
        const MomGroup &grp = momtab.groups[g];
        int nops = (int)grp.ops.size();
        for(int i=0; i<nops; i++){
          for(int j=0; j<nops; j++){
            std::string tag = grp.frame + "_" + grp.irrep + "_c" + grp.comp + "_" + grp.ops[i].uid + "_" + grp.ops[j].uid;
            CorrFile cf;
            cf.data.assign(Craw[g].begin() + (i*nops + j) * T, Craw[g].begin() + (i*nops + j + 1) * T);
            if( WR ) write(*WR, "Cmomraw_" + tag, cf);
            if( doSinkSmear ){
              CorrFile cs;
              cs.data.assign(Crawss[g].begin() + (i*nops + j) * T, Crawss[g].begin() + (i*nops + j + 1) * T);
              if( WR ) write(*WR, "Cmomrawss_" + tag, cs);
            }
          }
        }
      }
    }
    std::cout << GridLogMessage << "momentum check: max rel |FFT(p=0) - sliceSum| over all projected pairs = " << maxP0 << std::endl;
    if( phaseWorst >= 0.0 ){
      std::cout << GridLogMessage << "phase-check summary: max rel = " << phaseWorst
                << (phaseWorst < 1.0e-10 ? " PASSED" : " FAILED") << std::endl;
    }
    std::cout << GridLogMessage << "wrote mom_meta + " << nMomWritten << " Cmom datasets"
              << (momRaw ? " (+ Cmomraw)" : "") << (doSinkSmear ? " (+ smeared-sink copies)" : "") << std::endl;
  }

  if( doNaive ){
    std::cout << GridLogMessage << "naive-check summary: " << (naiveOK ? "PASSED" : "FAILED") << std::endl;
  }
  std::cout << GridLogMessage << "wrote " << outFile << ": meta + " << pairs.size() << " Cel + "
            << copNames.size() << " Cop datasets" << (doSinkSmear ? " (+ smeared-sink copies)" : "") << std::endl;

  Grid_finalize();
}
